name = "dropbox"


[namespace.storage]
implement = ["appender"]

[namespace.storage.new]
required = ["credential"]
optional = ["work_dir", "default_storage_pairs", "http_client_options", "pair_policy"]

[namespace.storage.op.delete]
optional = ["multipart_id"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.upload-session-id]
type = "string"